"""Migration Init

Revision ID: f16de3e17c09
Revises: 
Create Date: 2024-08-23 18:17:56.015086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16de3e17c09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nasabah',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('no_hp', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rekening',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nasabah_id', sa.UUID(), nullable=False),
    sa.Column('no_rekening', sa.String(), nullable=False),
    sa.Column('saldo', sa.Float(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nasabah_id'], ['nasabah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rekening_id', sa.UUID(), nullable=False),
    sa.Column('no_rekening', sa.String(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('tipe_transaksi', sa.Enum('TABUNG', 'TARIK', name='tipe_transaksi'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rekening_id'], ['rekening.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('rekening')
    op.drop_table('nasabah')
    # ### end Alembic commands ###
